name: Winlator Rootfs Test (use BCC)

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      inputDlUrl:
        description: "Download Rootfs(tzst) URL"
        required: true
        default: "1.27.2"

jobs:
  BCC:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: BCC
        run: |
          export 
          echo "####"
          env
          echo "####"
          ls $GITHUB_WORKSPACE
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
